vlog -work work C:/altera/13.0sp1/ScalingUnit/simulation/modelsim/Waveform1.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.ScalingUnit_vlg_vec_tst
onerror {resume}
add wave {ScalingUnit_vlg_vec_tst/i1/clk}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[31]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[30]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[29]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[28]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[27]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[26]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[25]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[24]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[23]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[22]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[21]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[20]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[19]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[18]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[17]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[16]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[15]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[14]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[13]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[12]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[11]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[10]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[9]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[8]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[7]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[6]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[5]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[4]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[3]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[2]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[1]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_in[0]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_out}
add wave {ScalingUnit_vlg_vec_tst/i1/data_out[7]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_out[6]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_out[5]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_out[4]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_out[3]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_out[2]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_out[1]}
add wave {ScalingUnit_vlg_vec_tst/i1/data_out[0]}
add wave {ScalingUnit_vlg_vec_tst/i1/rst_n}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[31]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[30]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[29]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[28]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[27]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[26]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[25]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[24]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[23]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[22]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[21]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[20]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[19]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[18]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[17]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[16]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[15]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[14]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[13]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[12]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[11]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[10]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[9]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[8]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[7]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[6]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[5]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[4]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[3]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[2]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[1]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_M[0]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_N}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_N[4]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_N[3]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_N[2]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_N[1]}
add wave {ScalingUnit_vlg_vec_tst/i1/scale_N[0]}
add wave {ScalingUnit_vlg_vec_tst/i1/valid_in}
add wave {ScalingUnit_vlg_vec_tst/i1/valid_out}
run -all
